### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by scottshipman**

### CODE REVIEW

**Comment by scottshipman** [comment]
This is a first pass at what a PR Risk template would look like...we can use this PR as discussion to improve prior to merging and adding to other bundles.

**Comment by heathdutton** [comment]
Looks great to me!

**Comment by heathdutton** [comment]
**Please be sure you are submitting this against the _master_ branch.**

[//]: # This Pull Request (Place an 'X' for each):
```
| Q  |   Risk Level                         | NO  | Low | High |
|                           |     |     |      |
| Alters Lead Data?                         |     |     |      |
| Schema Change?                            |     |     |      |
| Adds A Query or Modifies Existing Query?  |     |     |      |
| Adds or Modifies Existing Auto-Enhancer?  |     |     |      |
| Modifies Ingestion Process?               |     |     |      |
| Modifies sendContact Data?                |     |     |      |
```

[//]: # ( Required: )
#### Description:

**Comment by heathdutton** [comment]
Should end up looking like this:

| Risk Level                                | No | Low | High |
| ----------------------------------------- | -- | --- | ---- |
| Alters Lead Data?                         |    |     |      |
| Schema Change?                            |    |     |      |
| Adds A Query or Modifies Existing Query?  |    |     |      |
| Adds or Modifies Existing Auto-Enhancer?  |    |     |      |
| Modifies Ingestion Process?               |    |     |      |
| Modifies sendContact Data?                |    |     |      |

**Pull request merged**
